---
title: "ChartGen"
author: "Yu Yuen Hern"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(sf)
library(ggplot2)
library(urbnmapr)
library(ggplot2)
library(readxl)
library(readr)
library(plyr)
library(dplyr)
library(pastecs)
library(tidyverse)
# library(mapview)
library(xlsx)

```


```{r}
df <- read_excel("occurrence_2010.xlsx")
df <- na.omit(df)
df
```


```{r}
counts <- ddply(df, .(df$eventDate, df$species, df$year), nrow)
names(counts) <- c("eventDate", "species", "year", "Freq")

dateVector <- as.Date(c("1990-11-01", "2018-02-21"))

counts %>% 
  filter(eventDate >= dateVector[1] & eventDate <= dateVector[2]) %>% # reactive input here
  # filter((species == "Litoria fallax")) %>% # reactive input here
  ggplot(aes(x = eventDate, y = Freq, color = species)) + 
  geom_line(aes(group = species)) + 
  geom_point()
```

```{r}

year_input = 2002

counts %>% 
  filter(year == year_input) %>% # reactive input here
  # filter((species == "Litoria fallax")) %>% # reactive input here
  ggplot(aes(x = Freq, y = species)) + 
  geom_col(aes(fill = species))
```


```{r}
df %>%
  filter(year >= 2006) %>%   # reactive input here
  # filter((species == "Litoria fallax" | species == 0)) %>%
  mapview(xcol = "decimalLongitude", ycol = "decimalLatitude", zcol = "species", crs = 4269, grid = FALSE)
```