---
title: 'Frog Discovery Tool: A monitoring tool to detect frog occurrences based on identified
  sample frog species'
author: "The Katak Detector"
date: Nurhanie Syakirah (S2132021), Yu Yuen Hern (S2121801), Nor Shaffilza (S2156225), Aina Shamsuddin (S2138897), Dong Xiaoran (S2131591)
output:
  slidy_presentation: default
  powerpoint_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, warning=FALSE, message=FALSE)
```

## Background of the Project

Amphibians such as frogs and toads are strong indicator species for pollution. They have permeable skin through which they absorb oxygen and toxins. As a result, they’re extremely sensitive to changes in the quality of air and water. They’re often the first animals, for example, to be affected by pesticide use in or near their ecosystems. Scientists look to them to get a sense of the overall health of old-growth forest ecosystems and to monitor the effects of human-caused habitat changes.

Dataset: Frog occurrence dataset

>https://challenge.ey.com/challenges/level-2-global-frog-discovery-tool-EEmnW-5fR/data-description


## Introduction of Project

- Problem statements

The declination of frogs may be a warning to us that our planet is becoming unliveable. The disappearance of frogs is causing concerns such as increase of greenhouse effect, climate change & balance of ecosystem.

- Research questions

i.	    What are the frog trends that we can see from the dataset?
ii.	    When the frog’s population at its highest?
ii.	    When and where the frog’s population at its concerned rates?
iv.   	Which species is considered dominant population in Australia?

- Objectives & motivations

i.    By studying indicator species, scientists can keep a finger on the pulse of an entire ecosystem’s health without having to spread monitoring resources across multiple species and locations. Monitoring is key to prioritizing actions intended to protect and restore biodiversity.
ii.   This allows scientists not only to learn which populations of frog species are most at risk, but it also helps them protect frog populations and, crucially, their entire ecosystems.

- Target users
i.    Researchers & scientist
ii.   Governmental or non-profit organization
iii.    Law makers


## Data Science Methodology

- Formulating questions
  i.	Choose domain 
  ii.	Identify the current problem we are currently facing
- Data gathering
  i.	Consider many data resources such as github, Kaggle, EY
- Data Cleaning
  i.	Drop irrelevant column
  ii.	Identify the missing values and decide on what to do with it
- EDA & Data visualization
  i.	Plot the trends using line graph and geospatial mapping
  ii.	Attempt to answer the initial questions
- Modelling & Prediction
- Deployment

Result:

To be able to develop a monitoring tool of frog occurrence for numbers of identified frog species across Australia, extract useful insight from it and project the prediction of frog occurrence. 

Shinyapps:

>https://yuenherny.shinyapps.io/thekatakdetector/


## Conclusions

a.    Ultimately, frogs are important to the world because they are essentially our “canary in the coal mine” when it comes to the environment. They are considered natural bioindicators, which is something that measures the health of the environment. Where frogs occur, we see healthy, thriving, resilient ecosystems.
b.    Monitoring indicator species can also better help scientists their research on ecology and biodiversity. For example, while a wetland ecosystem may show general signs that something is amiss, if scientists see that frog populations are plummeting, they’ll know the problem may be pesticides.
c.    Scientists, lawmakers, and public officials can also use the data collected from indicator species to implement conservation policies. For examples, protecting land and habitats, regulating development or chemical use, or passing laws to reverse or prevent damage before it becomes too late.

- Project challenges & limitations

Shinyapp allocates only maximum size of 1 GB for the Free and Starter plans

i.    Reduce the data up to 2020 since it can't handle more than 44k rows of data (Original data has 193792k rows)
ii.   Shinyapps keeps on crashing & disconnected from server due to too many data & memory usage of libraries used
iii.    Due to computation limits, we omitted the usage of mapview library as it consumed too much memory
iv.   Unable to showcase prediction outcome, since we dropped huge chunk of data

- Future recommendations

Build a computational model that can predict the count of frogs for a specific location using multiple datasets, and to validate model on other locations of other countries using a variety of open-source geospatial datasets available on Microsoft Planetary Portal (TerraClimate, Sentinel L-2, Copernicus Elevation, Esri 10m Land Cover and JRC Water Surface).

Frogs identifier with the image on every sampled species

- Related links:

>GitHub: https://github.com/yuenherny/The-Katak-Detector

>Rpubs: https://rpubs.com/Kirah/frogdetector

>Shinyapps: https://yuenherny.shinyapps.io/thekatakdetector/

>Dataset: https://challenge.ey.com/challenges/level-2-global-frog-discovery-tool-EEmnW-5fR/data-description


